### ISSUE TITLE
Predicates do not support Date.

### ISSUE THREAD

**Issue by paweldrozanski** [phstc/ransack_mongo#5]
Hi,

I've just faced a problem with predicates gt, lt, gteq and lteq. These predicates cast value to_f (in appropriate _matcher functions). It's ok, but the problem is when 'value' is Date type. Ransack_mongo should support different types than numeric.

Original ransack gem does the job correctly.

**Comment by phstc** [comment]
Hey @dr0p 

It was fixed by this commit: bef5ab5652cf4c2405bc3d803d5c66ac38e2f81e - I've just released a new version `1.0.1` including this fix. Could you bump ransack_mongo?

**Comment by paweldrozanski** [comment]
Version bumped. It works like a charm. Thank You. @phstc
